In [1]:
import pandas as pd
subjects = ['01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21']

language = ['NNS', 'NNS', 'NNS', 'E', 'E', 'E', 'E', 'E', 'NNS', 'E', 'NNS', 'NNS', 'E', 'NNS', 'NNS', 'NNS', 'E', 'NNS', 'E', 'E', 'E'] 

hand = ['R','R','L','R','R','R','R','A','L','R','R','R','R','R','R','R','R','R','R','R','R']
eeg_df = pd.DataFrame()
temp = 0

In [2]:
#For each of the 21 subjects, read the EEG csv file, add native language and dominant hand features. 
for subject in subjects:
    eeg_file_path = './scottwellington-FEIS-7e726fd/experiments/'+subject+'/thinking.csv'
    temp_df = pd.read_csv(eeg_file_path)
    
    if (language[temp] == 'NNS'): 
        temp_df['Non-native'] = 1
        temp_df['English'] = 0 
    else:
        temp_df['English'] = 1
        temp_df['Non-native'] = 0
    
    if (hand[temp] == 'R'):
        temp_df['Right'] = 1
        temp_df['Left'] = 0
        temp_df['Amb'] = 0
    elif (hand[temp] == 'L'):
        temp_df['Right'] = 0
        temp_df['Left'] = 1
        temp_df['Amb'] = 0
    else:
        temp_df['Right'] = 0
        temp_df['Left'] = 0
        temp_df['Amb'] = 1

    #temp_df['Lang'] = language[temp]
    #temp_df['Hand'] = hand[temp]

    eeg_df = pd.concat([eeg_df,temp_df])
    temp = temp+1
print(eeg_df.head())

   Time:256Hz  Epoch           F3          FC5          AF3           F7  \
0   11.000000      0  4237.179688  4235.512695  4254.487305  4268.077148
1   11.003906      0  4239.871582  4239.487305  4251.153809  4277.436035
2   11.007812      0  4240.000000  4239.871582  4245.256348  4285.000000
3   11.011719      0  4238.461426  4237.692383  4239.871582  4287.948730
4   11.015625      0  4237.051270  4234.615234  4238.589844  4286.153809

            T7           P7           O1           O2  ...          FC6  \
0  4245.256348  4250.128418  4224.230957  4242.948730  ...  4241.922852
1  4245.384766  4251.153809  4226.538574  4245.384766  ...  4246.153809
2  4247.563965  4251.538574  4229.358887  4246.538574  ...  4249.487305
3  4250.897461  4252.692383  4232.051270  4247.948730  ...  4250.000000
4  4254.871582  4255.641113  4234.358887  4250.897461  ...  4247.563965

            F4  Label     Stage  Flag  Non-native English Right  Left  Amb
0  4275.897461  goose  thinking   NaN           1       0     1     0    0
1  4280.384766  goose  thinking   NaN           1       0     1     0    0
2  4280.897461  goose  thinking   NaN           1       0     1     0    0
3  4276.922852  goose  thinking   NaN           1       0     1     0    0
4  4271.153809  goose  thinking   NaN           1       0     1     0    0

[5 rows x 24 columns]

In [3]:
eeg_df.head()

,Time:256Hz,Epoch,F3,FC5,AF3,F7,T7,P7,O1,O2,...,FC6,F4,Label,Stage,Flag,Non-native,English,Right,Left,Amb
0,11.000000,0,4237.179688,4235.512695,4254.487305,4268.077148,4245.256348,4250.128418,4224.230957,4242.948730,...,4241.922852,4275.897461,goose,thinking,NaN,1,0,1,0,0
1,11.003906,0,4239.871582,4239.487305,4251.153809,4277.436035,4245.384766,4251.153809,4226.538574,4245.384766,...,4246.153809,4280.384766,goose,thinking,NaN,1,0,1,0,0
2,11.007812,0,4240.000000,4239.871582,4245.256348,4285.000000,4247.563965,4251.538574,4229.358887,4246.538574,...,4249.487305,4280.897461,goose,thinking,NaN,1,0,1,0,0
3,11.011719,0,4238.461426,4237.692383,4239.871582,4287.948730,4250.897461,4252.692383,4232.051270,4247.948730,...,4250.000000,4276.922852,goose,thinking,NaN,1,0,1,0,0
4,11.015625,0,4237.051270,4234.615234,4238.589844,4286.153809,4254.871582,4255.641113,4234.358887,4250.897461,...,4247.563965,4271.153809,goose,thinking,NaN,1,0,1,0,0

In [4]:
eeg_df.tail()

,Time:256Hz,Epoch,F3,FC5,AF3,F7,T7,P7,O1,O2,...,FC6,F4,Label,Stage,Flag,Non-native,English,Right,Left,Amb
204795,3513.980469,159,4233.077148,4243.974121,4224.743652,4232.820312,4265.512695,4231.794922,4236.666504,4240.000000,...,4257.179688,4247.307617,s,thinking,NaN,0,1,1,0,0
204796,3513.984375,159,4235.641113,4242.051270,4229.358887,4233.205078,4270.256348,4231.025879,4240.897461,4241.794922,...,4259.743652,4251.666504,s,thinking,NaN,0,1,1,0,0
204797,3513.988281,159,4239.743652,4242.692383,4236.922852,4233.846191,4273.333496,4229.358887,4242.948730,4242.692383,...,4263.974121,4254.871582,s,thinking,NaN,0,1,1,0,0
204798,3513.992188,159,4242.948730,4246.025879,4243.974121,4234.743652,4275.641113,4227.820312,4242.307617,4241.794922,...,4266.922852,4255.769043,s,thinking,NaN,0,1,1,0,0
204799,3513.996094,159,4244.615234,4249.871582,4247.820312,4236.282227,4278.333496,4227.563965,4240.000000,4239.487305,...,4267.436035,4255.256348,s,thinking,NaN,0,1,1,0,0

In [5]:
print(len(eeg_df))

4239360

In [6]:
y = eeg_df.Label

In [7]:
feature_names = ['F3','FC5','AF3','F7','T7','P7','O1','O2','P8','T8','F8','AF4','FC6','F4','Non-native','English','Right','Left','Amb']

In [8]:
X = eeg_df[feature_names]

In [9]:
from sklearn.tree import DecisionTreeClassifier
eeg_model = DecisionTreeClassifier(random_state=1)
eeg_model.fit(X, y)

DecisionTreeClassifier(random_state=1)

In [10]:
predicitons = eeg_model.predict(X)

In [11]:
from sklearn.model_selection import train_test_split
train_X, val_X, train_y, val_y = train_test_split(X, y, random_state = 0, shuffle=True)
eeg_model = DecisionTreeClassifier(random_state=0)
eeg_model.fit(train_X, train_y)
val_predictions = eeg_model.predict(val_X)
final_eeg_model = DecisionTreeClassifier(max_leaf_nodes=100, random_state=1)

In [12]:
final_eeg_model.fit(X, y)

DecisionTreeClassifier(max_leaf_nodes=100, random_state=1)

In [13]:
from sklearn.metrics import accuracy_score
print(accuracy_score(val_y, val_predictions))

0.5365998641304348

In [14]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(random_state=1)
rf_model.fit(train_X, train_y)
rf_preds = rf_model.predict(val_X)

In [15]:
print("Random Forest Accuracy Score:")
print(accuracy_score(val_y, rf_preds))

Random Forest Accuracy Score:
0.8607025588768116